### ISSUE TITLE
Nullpointer exception for newer replays?

### ISSUE THREAD

**Issue by dsjoho** [ykim/euls#2]
Hi,
I tried running the provided example program for a couple of replays, but turned into the following error for everything that wasn't the provided .dem file.

```
2015-02-02 19:09:32,548 [main] [] INFO  - 00:00.000
2015-02-02 19:09:32,551 [main] [] INFO  - Match Id : null
2015-02-02 19:09:32,560 [main] [] INFO  - Match Type : null
2015-02-02 19:09:32,561 [main] [] INFO  - Match Time : null
2015-02-02 19:09:33,077 [main] [] INFO  - 01:10.333
2015-02-02 19:09:33,077 [main] [] INFO  - Match Id : null
2015-02-02 19:09:33,077 [main] [] INFO  - Match Type : null
2015-02-02 19:09:33,077 [main] [] INFO  - Match Time : null
2015-02-02 19:09:33,162 [main] [] INFO  - 00:25.000
Exception in thread "main" java.lang.NullPointerException
    at skadistats.clarity.model.Entity.getProperty(Entity.java:57)
    at ykim.euls.Utils.getPropertyFromEntity(Utils.java:65)
    at ykim.euls.models.protobuf.base.EntityBase.valueOfProperty(EntityBase.java:38)
    at ykim.euls.models.protobuf.base.EntityBase.getProperty(EntityBase.java:21)
    at ykim.euls.models.protobuf.GameRules.getMatchId(GameRules.java:30)
    at ykim.euls.example.App.run(App.java:32)
    at ykim.euls.example.App.main(App.java:18)
```

The 4 files that I've tested (and all fail) are in the range of 110000000.dem to 1200000000.dem, and can be provided if you'd like.

**Comment by ykim** [comment]
Unfortunately, I'm not surprised to hear this. The issue is that Valve has actually changed the structure of the replays over time. The current iteration of euls is built to work against the latest replay formats. Ideally, I would get around to having euls be able to detect the version type, but that is kind of on a wishlist for now.

**Comment by ykim** [comment]
Can you provide the replays? This sounds odd because it's been working on some personal replays of mine on that range.

**Comment by dsjoho** [comment]
Here, just uploaded one of them. Also that range should be within the last week-month, otherwise I failed something..
http://www.filedropper.com/1116163630
